config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # namespace :admin do
  # resources :requests do
  #   collection do
  #     put 'accept_all'
  #     put 'reject_all'
  #     end
  #   end
  # end

  resources :products
  resources :users

  post "/auth/login", to: "authentication#login"

  resources :passwords, only: [:update]

  resources :password_resets, only: [:edit, :update]


  resources :password_resets do
   get :show_error, on: :collection
   get :edit_error, on: :collection
  end

    # resources :carts

  post "/add_product/:id", to: "carts#add_product"
  delete "/remove_product/:id", to: "carts#remove_product"

  # resources :products

  # get '/admin/product', to: 'admin#'
  # get '/admin/product/upload_csv', to: 'admin#upload_csv'


  resources :products do
    collection do
    post :import_csv
    get  :import_csv
    end
  end

  get "/my_cart",  to: "carts#view_cart"

  # wishlist 

  # resources :wishlists, only: [:index, :create, :destroy]

  post "/add_product_wishlist/:id", to: "wishlists#add_product_to_wishlist"
  delete "/remove_product_wishlist/:id", to: "wishlists#remove_product_to_wishlist"
  get "/my_wishlist", to: "wishlists#view_wishlist"


  #  addresses

  resources :addresses

  resources :orders

  resources :notifications

# stripe payment

  # post "/payments", to: "payments#create"
   post "/payments/checkout", to: "payments#checkout"
   get  "/payments/retrive_checkout", to: "payments#retrive_checkout"


   resources :terms_and_conditions

   # add request of the veders to sell or items in our eCommerce Plateform

  # resources :requests, only: [] do
  #   patch :accept
  #   patch :reject
  # end

   resources :requests

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
# before_action :authenticate_request, except: [:create]
  def new
    # @user = User.new
  end
    
  def create
    @user = User.find_by(email: params[:user_email])
    if @user.present?
      @user.generate_reset_password_token
      PasswordMailer.reset_password(@user).deliver_now
      render json: {notice: "Reset password email sent successfully"}, status: :ok
    else
      render json: {notice: "Invalid email address"} , status: :unprocessable_entity 
    end
  end

  def show_error
  end

  def edit
    @user = User.find_by(reset_password_token: params[:id])
  # if @user.nil?
  # flash[:alert] = 'Invalid reset password token.'
  # redirect_to root_path # or any other appropriate path
  # end
  end

  def update
    @user = User.find_by(reset_password_token: params[:id])
    if @user && @user.reset_password_period_valid?
      if @user.update(password_params)
        @user.mark_reset_password_as_used
        redirect_to new_password_reset_path, notice: 'Password reset successful'
      else
          redirect_to edit_error_password_resets_path: 'Password update failed'
      end
      else
        redirect_to show_error_password_resets_path, notice: 'invalid or expired tocken'

        # redirect_to show_password_reset_path, notice: 'invalid or expired tocken'
        end
    end

  private 
  def password_params
      params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/password_resets/edit.html.erb
<!-- <div style="display: flex; justify-content: center; align-items: center; flex-direction: column;"> -->
<style >
  .abc{
    padding: 10px;
    margin: 10px;
    width: 500px;
  }
</style>
<h1>Reset Password</h1>
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class='error_messages'>
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<table>
 <tr> <div class='field abc'>
    <td width="3vw"><%= f.label :password %></td>
   <td> <%= f.password_field :password %></td>
  </div></tr>
  <tr><div class='field abc'>
    <td><%= f.label :password_confirmation %></td>
    <td><%= f.password_field :password_confirmation %></td>
  </div></tr>
</table>
  <div class='actions'><%= f.submit 'Update password' %></div>
<% end %>
<!-- </div> -->

app/views/password_resets/edit_error.html.erb
<h1>Confirm password is not matched</h1>

app/views/password_resets/new.html.erb
<h1>Your password has been reset successfully!</h1>
 

app/views/password_resets/show_error.html.erb
<div>
  <h1>Invalid or expired token. Please request a new password reset.</h1>
</div>